name: database

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    hostname: postgres
    networks:
      - dbnet
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:?database password not set}
      POSTGRES_USER: ${PGPUSER:?database user not set}

    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin
    networks:
      - dbnet
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGAEMAIL:?pgadmin email not set}
      PGADMIN_DEFAULT_PASSWORD: ${PGAPASSWORD:?pgadmin password not set}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:

networks:
  dbnet:
    driver: bridge