name: postgresv1

services:
  postgres:
  image: postgres:12.3-alpine
  restart: always
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
  volumes:
    - postgres:/var/lib/postgresql/data

networks:
  mynet:
    driver: bridge
